# Generated by Django 4.0.5 on 2022-06-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='This is the post tag of this post', max_length=255),
        ),
    ]
